### ISSUE TITLE
Questions on the implementation

### ISSUE THREAD

**Issue by drvarya** [ale3otik/paraphrases-generator#1]
Hi Aleksey, had a couple of questions on the implementation, hoping you can get back.

1. How long do you train the model for and did you change any of the hyperparameters mentioned in the paper.
2. In the paper the authors mention that they are learning the embeddings instead of using glove did you see an improvement with glove ?
3. Can you share a pretrained model to bootstrap and reduce training time.

Thanks

**Comment by ale3otik** [comment]
Hi Dhruv, 

1. It takes 150k - 300k iterations to converge, ~ 6-8 hours with single nvidia-P100. I did adjust decoder state, encoder state and vocab sizes depend on training dataset size. I've tried to combine datasets described in the paper + snli. In the notebook "plotter.ipynb" there are some plots and bleu scores for various settings. Name "quora_coco_200kit_600_800" means that there were used QUORA and MSCOCO datasets for training, 200k iterations, encoder-state-size=600,decoder-state-size=800.

2. I was trying to apply this model to extend some small dataset. If transfer to new dataset, glove finds embeddings for words never seen in training (new dataset adds up to ~10% of new words ). That's the logic, but I didn't actually try to train internal embeddings. However I use "higway" architecture to adjust glove to specified task, credited from original RVAE implementation. 

3. It's to large to add to github, You can ping me directly to aleksey.zotov@phystech.edu and I'll try to send it then.

**Comment by drvarya** [comment]
Thank you for the information that provides good clarity.
