### ISSUE TITLE
How to generate examples of paraphrase sentences?

### ISSUE THREAD

**Issue by kj-lai** [ale3otik/paraphrases-generator#3]
Looking through the notebooks, I still can't figure out how to generate a paraphrased sentence. Does this package includes function similar to `model.predict()`? So that it will take a string as input and provide a paraphrased string as output. Thanks in advance.

**Comment by ale3otik** [comment]
There is an example in **mscoco_captions_understanding.ipynb**.

First you need to init BatchLoader with the exact data and config you train it on.
Then in function `paraphrases_from_sources(...)` you can see:
```
input = batch_loader.input_from_sentences([[s1],[s2]])
input = [var.cuda() if args.use_cuda else var for var in input]
result += [paraphraser.sample_with_input(batch_loader, args.seq_len, args.use_cuda, use_mean, input)]
```
It generates input from pair of sentences and then uses this input to generate paraphrase.

Model knows only how to generate paraphrases from pairs, so if you want to generate it for single sentence just set it to both first and second input like:
`input = batch_loader.input_from_sentences([[sentence],[sentence]])`

**Comment by kj-lai** [comment]
I ran throught the notebook `mscoco_captions_understanding.ipynb`

But got stucked at the `batch_loader` with the error
`[Errno 2] No such file or directory: '../InferSent/dataset/SNLI/s1.train'`

Could u include the SNLI or InferSent dataset in your repos?

**Comment by ale3otik** [comment]
Here you can find dataset https://nlp.stanford.edu/projects/snli/. 
Parser for the dataset you can find in utils/batch_loader.py

Similar actions you need to take to gather other datasets if needed (MSCOCO, InferSent, Quora Question Pairs).

**Comment by kj-lai** [comment]
@ale3otik thank you for your detailed explanation. 

It seems that i would have to train the model myself, could you explain what `snli_200kit_600_800` means? What i know is snli dataset with 200k iterations, but i dont know what does the rest indicates.

**Comment by ale3otik** [comment]
encoder_rnn_size, decoder_rnn_size respectively.

**Comment by kj-lai** [comment]
How did u create `infersent.allnli.pickle` ? I think u miss this out in the `mscoco_captions_understanding.ipynb` example

**Comment by ale3otik** [comment]
It's pretrained sentence embeddings from facebook. You can find detailed instructions here https://github.com/facebookresearch/InferSent .

But it's not used for paraphrase generation. Only for some further analysis.

**Comment by kj-lai** [comment]
Noted, i have no further questions. Thanks for your advice.
