### ISSUE TITLE
Is there a pretrained model ready?

### ISSUE THREAD

**Issue by exnx** [ale3otik/paraphrases-generator#5]
Hi!  Thanks for providing this code.

I was planning to just test this on my own sentence pairs and see how well it works.  Do you happen to have a pretrained model to share as well?  That would be amazing.  Thanks!

Eric

**Comment by ale3otik** [comment]
Model weights for model trained on joined quora + coco 200kit enc:600 dec:600.
https://drive.google.com/file/d/1hg5OB5AudlMS5jlH4ycmVjOKhbQjYZCb/view?usp=sharing

**Comment by exnx** [comment]
Hi!  Thanks for providing that.  I'm trying to just generate a paraphrase on some dataset, like Quora test questions.

When I tried to use this model on the sample.py file, I got the following error.  Any tips on the quickest way to test your pretrained model?  Thanks!

---

(py36) dhcp-nyc-403:paraphrases-generator ericnguyen$ python sample.py --model-name quora_coco_200kit_600_600 --use-quora True
use mean False
QUORA: train: 134336, test: 14927
ALL: train: 134336, test: 14927
Found 27522(/29559) words with glove vectors
Vocab size : 27522
Traceback (most recent call last):
  File "sample.py", line 80, in <module>
    paraphraser.load_state_dict(t.load('saved_models/trained_paraphraser_' + args.model_name, map_location='cpu'))
  File "/anaconda/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Paraphraser:
	size mismatch for decoder.fc.weight: copying a param with shape torch.Size([25000, 600]) from checkpoint, the shape in current model is torch.Size([20000, 600]).
	size mismatch for decoder.fc.bias: copying a param with shape torch.Size([25000]) from checkpoint, the shape in current model is torch.Size([20000]).

**Comment by ale3otik** [comment]
Seems to be vocab size mismatch,  you can probably fix it in `/utils/batch_loader.py` by setting `vocab_size=25000 (or 20000)`. 

There is an actual problem to use pretrained model, vocabulary matching is not saved as param and calculated at run time after each restart, and it depends on dataset used. If you use different dataset (or it's subset) you'll get vocab mismatch for the output stage (for the input stage probably too).
